apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: job-celery-mon
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: job-celery-mon
    spec:
      containers:
      - name: yadage-service-webui
        image: recast/celery-mon
        imagePullPolicy: Always
        command: ['sh','-c', 'flower --broker=${CELERY_BROKER_URL} --broker_api=${CELERY_BROKER_URL}']
        resources:
          requests:
            cpu: "0.5"
        ports:
          - containerPort: 5555
            name: "http"
        env:
          - name: CELERY_BROKER_URL
            value: 'redis://recast-backend-msg-queue.default.svc.cluster.local:6379/1'
---
apiVersion: v1
kind: Service
metadata:
  name: job-celery-mon
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5555
    name: http
    protocol: TCP
  selector:
    app: job-celery-mon
