apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storage-view
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: storage-view
    spec:
      containers:
      - name: storage-view
        image: python:2.7
        imagePullPolicy: Always
        command: ['python','-m','SimpleHTTPServer']
        workingDir: /data
        ports:
          - containerPort: 8000
            name: "http"
        volumeMounts:
          - name: cephfs
            mountPath: /data
            readOnly: true
      volumes:
      - name: cephfs
        cephfs:
          monitors:
          - 128.142.36.227:6790
          - 128.142.39.77:6790
          - 128.142.39.144:6790
          path: /volumes/_nogroup/b9949045-1e0c-43d2-841a-481714a11243
          user: recast-ceph-auth
          secretRef:
            name: ceph-secret-recastauth
          readOnly: true
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: storage-view
  name: storage-view
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: storage-view
