apiVersion: v1
kind: Secret
metadata:
  name: control-center-ssl
type: Opaque
data:
  server.crt: |-
    {{ .Values.files.cc_ssl_crt }}
  server.key: |-
    {{ .Values.files.cc_ssl_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: control-center-config
type: Opaque
data:
  config.yaml: |-
    {{ .Values.files.cc_config_yaml }}
---
apiVersion: v1
kind: Secret
metadata:
  name: control-center-backendconfig
type: Opaque
data:
  backendconfig.yml: |-
    {{ .Values.files.cc_backendconfig_yaml }}
---
apiVersion: v1
kind: Secret
metadata:
  name: control-center-oauth
type: Opaque
data:
  app_id: {{ .Values.OAuth.control_center.app_id | b64enc }}
  secret: {{ .Values.OAuth.control_center.secret | b64enc }}
