CERNGitLab:
  User: mycernuser
  Password: mycernpassword
DNS:
  interactive_host: wflow-int
HostOverlays: false
ImagePullPolicy: Always
ImageTags:
  wflow_server: git-master
  wflow_logging: git-master
  worker: git-master
InternalServiceType: ClusterIP
ResourceRequirements: true
files:
  getkrb_sh: aGVsbG93b3JsZA==
  getmyproxy_sh: aGVsbG93b3JsZA==
  grid_crt: aGVsbG93b3JsZA==
  grid_key: aGVsbG93b3JsZA==
  krb_keytab: aGVsbG93b3JsZA==
  shiptarget_id_rsa: aGVsbG93b3JsZA==
  shiptarget_id_rsa_pub: aGVsbG93b3JsZA==
grid_pw: grid_pw
wflowserver:
  wflowslots: 10
yadage_load_token: yadage_load_token
infra:
  msg_queue: infra-msg-queue.default.svc.cluster.local
  database: infra-db.default.svc.cluster.local
wflowsvcclaim: wflowsvc-data
wflowworkerclaim: wflowworker-data
data_download_token: data_download_token
