apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storage-view
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: storage-view
    spec:
      containers:
      - name: storage-view
        image: python:2.7
        imagePullPolicy: Always
        command: ['python','-m','SimpleHTTPServer']
        workingDir: /data
        ports:
          - containerPort: 8000
            name: "http"
        volumeMounts:
          - name: worker
            mountPath: /data/worker
            readOnly: true
          - name: frontend
            mountPath: /data/frontend
            readOnly: true
          - name: control-center
            mountPath: /data/controlcenter
            readOnly: true
      volumes:
      - name: worker
        persistentVolumeClaim:
          claimName: worker-data
      - name: frontend
        persistentVolumeClaim:
          claimName: frontend-data
      - name: control-center
        persistentVolumeClaim:
          claimName: control-center-data
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: storage-view
  name: storage-view
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: storage-view
