apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: control-center
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: control-center
    spec:
      containers:
      - name: control-center
        image: recast/control-center:localbuild
        imagePullPolicy: Always
        command: ['recast-control-center','server','--config','/secrets/config/config.yaml']

        resources:
          requests:
            cpu: "1"

        ports:
          - containerPort: 8000
            name: "http"
            hostPort: 443
        volumeMounts:
          - name: ssl
            mountPath: /secrets/ssl
            readOnly: true
          - name: config
            mountPath: /secrets/config
            readOnly: true
          - name: backendconfig
            mountPath: /secrets/backend
            readOnly: true
          - name: cephfs
            mountPath: /recastresults
            subPath: recastresults
            readOnly: true
        env:
          - name: RECAST_BACKENDCONFIGFILE
            value: /secrets/backend/backendconfig.yml
          - name: RECAST_SSL_CERTFILE
            value: /secrets/ssl/server.crt
          - name: RECAST_SSL_KEYFILE
            value: /secrets/ssl/server.key
          - name: RECAST_APIURL
            value: https://frontend.default.svc.cluster.local:81/
          - name: RECAST_CELERY_REDIS_HOST
            value: recast-backend-msg-queue.default.svc.cluster.local
          - name: RECAST_CELERY_REDIS_PORT
            value: '6379'
          - name: RECAST_CELERY_REDIS_DB
            value: '0'
          - name: RECAST_SSL_VERIFY
            value: 'false'
          - name: RECAST_BASEURL
            value: https://recast-control.cern.ch/
          - name: RECAST_OAUTH_DUMMYLOGIN
            value: 'true'
          - name: RECAST_RESULT_BASE
            value: /recastresults
          - name: RECAST_BACKENDCONFIGURL
            value: https://raw.githubusercontent.com/recast-hep/recast-backend/master/recastbackend/resources/backendconfig.yml
      volumes:
      - name: ssl
        secret:
          secretName: control-center-ssl
      - name: config
        secret:
          secretName: control-center-config
      - name: backendconfig
        secret:
          secretName: control-center-backendconfig
      - name: cephfs
        cephfs:
          monitors:
          - 128.142.36.227:6790
          - 128.142.39.77:6790
          - 128.142.39.144:6790
          path: /volumes/_nogroup/b9949045-1e0c-43d2-841a-481714a11243
          user: recast-ceph-auth
          secretRef:
            name: ceph-secret-recastauth
          readOnly: true
      nodeSelector:
        ccnode: 'true'
