apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: lukasheinrich/recast-frontend
        imagePullPolicy: Always
        command: ['recast-frontend','server','--config','/secrets/config/config.yaml']
        resources:
          requests:
            cpu: "1" 
        ports:
          - containerPort: 5001
            name: http
            hostPort: 443
        volumeMounts:
          - name: ssl
            mountPath: /secrets/ssl
            readOnly: true
          - name: config
            mountPath: /secrets/config
            readOnly: true
        env:
          - name: RECAST_SSL_CERT
            value: /secrets/ssl/server.crt
          - name: RECAST_SSL_KEY
            value: /secrets/ssl/server.key
          - name: RECAST_ORCID_REDIRECT_URI
            value: https://recast-frontend-beta.cern.ch/login
      - name: postgres
        resources:
          requests:
            cpu: "0.5"
        image: postgres:latest
        volumeMounts:
          - name: cephfs
            mountPath: /pgdata
            subPath: frontenddbdata
        env:
          - name: PGDATA
            value: /pgdata
        ports:
          - containerPort: 5432
            name: postgres
      - name: api
        image: lukasheinrich/recast-rest-server
        imagePullPolicy: Always
        command: ['bash','-c','sleep 10 && recast-api server --config /secrets/config/config.yaml']
        resources:
          requests:
            cpu: "1"
        env:
          - name: RECAST_SSL_CERT
            value: /secrets/ssl/server.crt
          - name: RECAST_SSL_KEY
            value: /secrets/ssl/server.key
        volumeMounts:
          - name: ssl
            mountPath: /secrets/ssl
            readOnly: true
          - name: config
            mountPath: /secrets/config
            readOnly: true
        ports:
          - containerPort: 5000
            name: rest
            hostPort: 8443
      volumes:
      - name: ssl
        secret:
          secretName: frontend-ssl
      - name: config
        secret:
          secretName: frontend-config
      - name: cephfs
        cephfs:
          monitors:
          - 128.142.36.227:6790
          - 128.142.39.77:6790
          - 128.142.39.144:6790
          path: /volumes/_nogroup/b9949045-1e0c-43d2-841a-481714a11243
          user: recast-ceph-auth
          secretRef:
            name: ceph-secret-recastauth
          readOnly: false
      nodeSelector:
        frontendnode: 'true'
