apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shiptarget
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shiptarget
    spec:
      containers:
      - name: shiptarget
        image: quay.io/macropin/sshd
        command: ['/entry.sh','bash','-c','cat /secrets/ssh/rsa.pub > /root/.ssh/authorized_keys; /usr/sbin/sshd -D -f /etc/ssh/sshd_config']
        volumeMounts:
          - name: ssh
            mountPath: /secrets/ssh
            readOnly: true
          - name: cephfs
            mountPath: /recastresults
            subPath: recastresults
        ports:
          - containerPort: 22
            name: ssh
      volumes:
      - name: ssh
        secret:
          secretName: control-center-ssh
      - name: redisstorage
        hostPath:
          path: /srv/ccdata/redisdata/ 
      - name: cephfs
        cephfs:
          monitors:
          - 128.142.36.227:6790
          - 128.142.39.77:6790
          - 128.142.39.144:6790
          path: /volumes/_nogroup/b9949045-1e0c-43d2-841a-481714a11243
          user: recast-ceph-auth
          secretRef:
            name: ceph-secret-recastauth
          readOnly: false
