apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wflow-logging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wflow-logging
    spec:
      containers:
      - name: logstash
        image: recast/wflow-logging:git-master
        imagePullPolicy: Always
        runAsUser: 0
        command: ['/usr/local/bin/docker-entrypoint','logstash','-f','/pipelines/logstash-simple.conf']
        resources:
          requests:
            cpu: "0.5"
        volumeMounts:
          - name: cephfs
            mountPath: /joblogs
            subPath: joblogs
          - name: cephfs
            mountPath: /wflowlogs
            subPath: wflowlogs
        env:
          - name: LOGSTASH_REDIS_HOST
            value: recast-backend-msg-queue.default.svc.cluster.local
      volumes:
      - name: cephfs
        persistentVolumeClaim:
          claimName: control-center-data
