apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wflow-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wflow-server
    spec:
      containers:
      - name: wflow-server
        image: recast/wflowserver:alpha
        imagePullPolicy: Always
        command: ['python','wflowserver/server.py']
        ports:
          - containerPort: 5000
        env:
          - name: RECAST_CELERY_REDIS_HOST
            value: recast-backend-msg-queue.default.svc.cluster.local
          - name: RECAST_CELERY_REDIS_PORT
            value: '6379'
          - name: RECAST_CELERY_REDIS_DB
            value: '0'
---
apiVersion: v1
kind: Service
metadata:
  name: wflow-server
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    name: http
    protocol: TCP
  selector:
    app: wflow-server
