apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: recast/yadage-worker:git-master
        imagePullPolicy: Always
        command:
        - sh
        - '-c'
        - >-
          mkdir -p ~/.ssh &&
          cp ~/ssh_data/rsa.key ~/.ssh/id_rsa &&
          chmod 0400 ~/.ssh/id_rsa &&
          celery worker -A recastcelery.fromenvapp:app -l debug -Q ${RECAST_QUEUE} --concurrency 4
        workingDir: /srv/workerdata
        volumeMounts:
          - name: ssh
            mountPath: /root/ssh_data
          - name: cephfs
            mountPath: /srv/workerdata
            subPath: workerdata
        resources:
          requests:
            cpu: "0.5"  #will only fit one per 8VCPU node, but don't want to completely stuff it
            memory: "0.2Gi" #2GB memory per core
        env:
          - name: RECAST_UPLOAD_DISABLE_KNOWN_HOST
            value: ok
          - name: RECAST_CELERY_REDIS_HOST
            value: recast-backend-msg-queue.default.svc.cluster.local
          - name: RECAST_CELERY_REDIS_PORT
            value: '6379'
          - name: RECAST_CELERY_REDIS_DB
            value: '0'
          - name: RECAST_QUEUE
            value: 'recast_yadage_queue'
          - name: RECAST_DOCKERHOST
            value: hello
          - name: RECAST_YADAGEBACKEND
            value: celery
          - name: C_FORCE_ROOT
            value: 'true'
          - name: RECAST_QUARANTINE_DIR
            value: /srv/workerdata/quarantine
          - name: PACKTIVITY_CELERY_REDIS_BROKER
            value: 'redis://recast-backend-msg-queue.default.svc.cluster.local:6379/1'
          - name: YADAGE_SCHEMA_LOAD_TOKEN
            valueFrom:
              secretKeyRef:
                name: yadageloadtoken
                key: token
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: NotIn
                values: [yadagesvc,frontendnode,ccnode]
      volumes:
      - name: ssh
        secret:
          secretName: control-center-ssh
      - name: cephfs
        persistentVolumeClaim:
          claimName: worker-data
