apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yadage-service-webui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: yadage-service-webui
    spec:
      containers:
      - name: yadage-service-webui
        image: yadage/yadage-service:git-master
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.5"
        ports:
          - containerPort: 5000
            name: "http"
            hostPort: 443
        volumeMounts:
          - name: ssl
            mountPath: /secrets/ssl
            readOnly: true
          - name: cephfs
            mountPath: /recastresults
            subPath: recastresults
            readOnly: true
        env:
          - name: YADAGE_WORKFLOW_SERVER
            value: http://wflow-server.default.svc.cluster.local
          - name: YADAGE_SHIPTARGET_USER
            value: root
          - name: YADAGE_SHIPTARGET_HOST
            value: recast-backend-shiptarget.default.svc.cluster.local
          - name: YADAGE_SHIPTARGET_PORT
            value: '2022'
          - name: YADAGE_RESULTBASE
            value: /recastresults/yadagesvc
          - name: YADAGE_WORKFLOW_QUEUE
            value: recast_yadage_queue
          - name: YADAGE_JOBDB_REDIS_HOST
            value: recast-backend-msg-queue.default.svc.cluster.local
          - name: YADAGE_JOBDB_REDIS_PORT
            value: '6379'
          - name: YADAGE_JOBDB_REDIS_DB
            value: '3'
          - name: YADAGE_SSL_KEY
            value: '/secrets/ssl/server.key'
          - name: YADAGE_SSL_CERT
            value: '/secrets/ssl/server.crt'
          - name: CERN_OAUTH_TOKENURL
            value: 'https://oauth.web.cern.ch/OAuth/Token'
          - name: CERN_OAUTH_AUTHORIZEURL
            value: 'https://oauth.web.cern.ch/OAuth/Authorize'
          - name: CERN_OAUTH_APPID
            value: yadage
          - name: CERN_OAUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: yadagewebuiauth
                key: oauth_secret
          - name: CERN_OAUTH_REDIRECT_ROUTE
            value: '/oauth'
          - name: CERN_OAUTH_BASEURL
            value: 'https://yadage.cern.ch'
          - name: CERN_ATLAS_TOKEN
            valueFrom:
              secretKeyRef:
                name: yadagewebuiauth
                key: bearer_token
      volumes:
      - name: cephfs
        persistentVolumeClaim:
          claimName: control-center-data
      - name: ssl
        secret:
          secretName: yadage-ssl
      nodeSelector:
        role: yadagesvcnode
---
apiVersion: v1
kind: Service
metadata:
  name: yadage-service-webui
spec:
  type: NodePort
  ports:
  - port: 443
    nodePort: 32453
    targetPort: 5000
    name: http
    protocol: TCP
  selector:
    app: yadage-service-webui
