version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /redisdata:/data
  interactive:
    image: lukasheinrich/recast-backend
    command: bash
    stdin_open: true
    tty: true
    environment:
      - CELERY_REDIS_HOST=redis
      - CELERY_REDIS_PORT=6379
      - CELERY_REDIS_DB=0
    volumes:
       - /recastresults:/recastresults
  monitor:
    image: kamon/grafana_graphite
    ports:
      - "8080:80"
      - "8081:81"
      - "8125:8125/udp"
