version: '2'
services:
  redis:
    command: 'redis-server --appendonly yes'
    volumes:
      - $PWD/recaststorage/redisdata:/data
    image: redis
    ports:
      - 6379:6379
  webserver:
    command: recast-control-center server
    #stdin_open: true
    #tty: true
    image: lukasheinrich/recast-control-center
    environment:
      - RECAST_CELERY_REDIS_HOST=redis
      - RECAST_CELERY_REDIS_PORT=6379
      - RECAST_CELERY_REDIS_DB=0
      - RECAST_RESULT_BASE=$PWD/recaststorage
      - RECAST_STORAGEPATH=$PWD/recaststorage
      - RECAST_ORCID=0000-0002-4048-7584
      - RECAST_APITOKEN=3141-5926-5358-979323
      - RECAST_SSL_CERTFILE=/ssl_files/server.crt
      - RECAST_SSL_KEYFILE=/ssl_files/server.key
      - RECAST_OAUTH_SECRET=mzBIqlnaAfZzUj23oFFMvg1lT1Mlj1EOMGpUds45D8o1
    volumes:
      - $PWD/recaststorage:$PWD/recaststorage
      - /root/recast-certs/recast-control.crt:/ssl_files/server.crt
      - /root/recast-certs/recast-control.key:/ssl_files/server.key
    ports:
      - 443:8000
  
  monitor:
    image: lukasheinrich/recast-clustermon
    ports:
      - "8080:80"
      - "8081:81"
      - "8125:8125/udp"
    volumes:
      - $PWD/recaststorage/clustermonitor/whisper:/opt/graphite/storage/whisper
      - $PWD/recaststorage/clustermonitor/grafana:/opt/grafana/data
      - $PWD/recaststorage/clustermonitor/graphite:/opt/graphite/storage/log
