apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yadage-service-webui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: yadage-service-webui
    spec:
      containers:
      - name: yadage-service-webui
        command: [python,yadageservice/app.py,run_server]
        image: yadage/yadage-service:{{.Values.ImageTags.yadage_web}}
        imagePullPolicy: {{.Values.ImagePullPolicy }}
        resources:
        {{ if eq .Values.ResourceRequirements true}}
          requests:
            cpu: "0.5"
        {{ end }}
        ports:
          - containerPort: 5000
            name: "http"
        {{ if eq .Values.HostPorts true}}
            hostPort: 443
        {{ end }}
        volumeMounts:
          - name: ssl
            mountPath: /secrets/ssl
            readOnly: true
          - name: wflowresults
            mountPath: /results
            subPath: results
            readOnly: true
          - name: data
            mountPath: /workflow_inputs
            subPath: workflow_inputs
            readOnly: false
          {{ if eq .Values.HostOverlays true}}
          - name: localoverlaycode
            mountPath: /code
          {{ end }}
        env:
          - name: YADAGE_UPLOADBASE
            value: /workflow_inputs
          - name: YADAGE_WORKFLOW_SERVER
            value: http://{{ .Values.services.wflowserver }}
          - name: YADAGE_SHIPTARGET_USER
            value: root
          - name: YADAGE_SHIPTARGET_HOST
            value: {{ .Values.services.shiptarget }}
          - name: YADAGE_SHIPTARGET_PORT
            value: '2022'
          - name: YADAGE_RESULTBASE
            value: /results/yadagesvc
          - name: YADAGE_WORKFLOW_QUEUE
            value: yadage_queue
          - name: YADAGE_JOBDB_URI
            value: 'postgres://postgres:postgres@{{ .Values.services.database }}'
          - name: YADAGE_SSL_KEY
            value: '/secrets/ssl/server.key'
          - name: YADAGE_SSL_CERT
            value: '/secrets/ssl/server.crt'
          {{ if eq .Values.OAuth.Dummy true}}
          - name: CERN_DUMMY_LOGIN
            value: 'yes'
          {{ end }}
          - name: CERN_OAUTH_TOKENURL
            value: 'https://oauth.web.cern.ch/OAuth/Token'
          - name: CERN_OAUTH_AUTHORIZEURL
            value: 'https://oauth.web.cern.ch/OAuth/Authorize'
          - name: CERN_OAUTH_APPID
            valueFrom:
              secretKeyRef:
                name: yadagewebui-oauth
                key: app_id
          - name: CERN_OAUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: yadagewebui-oauth
                key: secret
          - name: CERN_OAUTH_REDIRECT_ROUTE
            value: '/oauth'
          - name: CERN_OAUTH_BASEURL
            value: 'https://{{ .Values.DNS.yadage_service }}'
          - name: CERN_ATLAS_TOKEN
            valueFrom:
              secretKeyRef:
                name: yadagewebuiauth
                key: bearer_token
      volumes:
      - name: wflowresults
        persistentVolumeClaim:
          claimName: {{ .Values.resultsclaim }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.yadagesvcclaim }}
      - name: ssl
        secret:
          secretName: yadage-ssl
      {{ if eq .Values.HostOverlays true}}
      - name: localoverlaycode
        hostPath:
          path: {{ .Values.LocalOverlays.YadadageServerCode }}
      {{end}}
      {{ if eq .Values.NodeAffinity true}}
      nodeSelector:
        role: yadagesvcnode
      {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: yadage-service-webui
spec:
  type: {{ .Values.InternalServiceType }}
  ports:
  - port: 443
    nodePort: 32453
    targetPort: 5000
    name: http
    protocol: TCP
  selector:
    app: yadage-service-webui
