apiVersion: v1
kind: Secret
metadata:
  name: control-center-ssl
type: Opaque
data:
  server.crt: |-
    {{ .Values.files.cc_ssl_crt | b64enc }}
  server.key: |-
    {{ .Values.files.cc_ssl_key | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: control-center-config
type: Opaque
data:
  config.yaml: |-
    {{ .Values.files.cc_config_yaml | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: control-center-backendconfig
type: Opaque
data:
  backendconfig.yml: |-
    {{ .Values.files.cc_backendconfig_yaml | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: control-center-oauth
type: Opaque
data:
  app_id: {{ .Values.OAuth.control_center.app_id | b64enc }}
  secret: {{ .Values.OAuth.control_center.secret | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: control-center-ssh
type: Opaque
data:
  id_rsa: |-
    {{ .Values.files.cc_id_rsa | b64enc }}
  id_rsa.pub: |-
    {{ .Values.files.cc_id_rsa_pub | b64enc }}
