{{ if eq .Values.Storage.Type "cephfs"}}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: recast-cluster-pv-01
spec:
  capacity:
    storage: {{ .Values.Storage.CCSize }}
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      {{- range .Values.Storage.CephFS.Monitors }}
      - {{ . | quote }}
      {{- end }}
    path: {{ .Values.Storage.CephFS.Path }}
    user: recast-cephfs-user
    secretRef:
      name: ceph-secret-recastauth
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: recast-cluster-pv-02
spec:
  capacity:
    storage: {{ .Values.Storage.FrontendSize }}
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      {{- range .Values.Storage.CephFS.Monitors }}
      - {{ . | quote }}
      {{- end }}
    path: {{ .Values.Storage.CephFS.Path }}
    user: recast-cephfs-user
    secretRef:
      name: ceph-secret-recastauth
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: recast-cluster-pv-03
spec:
  capacity:
    storage: {{ .Values.Storage.WorkerSize }}
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      {{- range .Values.Storage.CephFS.Monitors }}
      - {{ . | quote }}
      {{- end }}
    path: {{ .Values.Storage.CephFS.Path }}
    user: recast-cephfs-user
    secretRef:
      name: ceph-secret-recastauth
{{end}}