apiVersion: v1
data:
  getkrb.sh: {{ .Values.files.getkrb_sh | b64enc }}
  getmyproxy.sh: {{ .Values.files.getmyproxy_sh | b64enc }}
  gridpw: {{ .Values.grid_pw | b64enc }}
  host.cert: {{ .Values.files.grid_crt | b64enc }}
  # kerberos.keytab: {{/* .Values.files.krb_keytab | b64enc */}}
  privkey.pem: {{ .Values.files.grid_key | b64enc }}
kind: Secret
metadata:
  name: atlas-auth
  namespace: default
type: Opaque