apiVersion: v1
data:
  getkrb.sh: {{ .Values.files.getkrb_sh }}
  getmyproxy.sh: {{ .Values.files.getmyproxy_sh }}
  gridpw: {{ .Values.grid_pw | b64enc }}
  host.cert: {{ .Values.files.grid_crt }}
  kerberos.keytab: {{ .Values.files.krb_keytab }}
  privkey.pem: {{ .Values.files.grid_key }}
kind: Secret
metadata:
  name: atlas-auth
  namespace: default
type: Opaque
