apiVersion: v1
kind: Secret
metadata:
  name: control-center-ssh
type: Opaque
data:
  id_rsa: |-
    {{ .Values.files.cc_id_rsa | b64enc }}
  id_rsa.pub: |-
    {{ .Values.files.cc_id_rsa_pub | b64enc }}
