apiVersion: v1
kind: Secret
metadata:
  name: frontend-ssl
type: Opaque
data:
  server.crt: |-
    {{ .Values.files.frontend_ssl_crt | b64enc }}
  server.key: |-
    {{ .Values.files.frontend_ssl_key | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-config
type: Opaque
data:
  config.yaml: |-
    {{ .Values.files.frontend_config_yaml | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-oauth
type: Opaque
data:
  app_id: {{ .Values.OAuth.frontend.app_id | b64enc }}
  secret: {{ .Values.OAuth.frontend.secret | b64enc }}
