{{ if eq .Values.Storage.Type "localfs"}}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: recast-cluster-pv-01
spec:
  capacity:
    storage: {{ .Values.Storage.CCSize }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.Storage.HostFS.CCPath }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: recast-cluster-pv-02
spec:
  capacity:
    storage: {{ .Values.Storage.FrontendSize }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.Storage.HostFS.FrontendPath }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: recast-cluster-pv-03
spec:
  capacity:
    storage: {{ .Values.Storage.WorkerSize }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.Storage.HostFS.WorkerPath }}

{{end}}