apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wflow-logging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wflow-logging
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: logstash
        image: recast/wflow-logging:{{.Values.ImageTags.wflow_logging}}
        imagePullPolicy: {{.Values.ImagePullPolicy }}
        command: ['/usr/local/bin/docker-entrypoint','logstash','-f','/pipelines/logstash-simple.conf']
        {{ if eq .Values.ResourceRequirements true}}
        resources:
          requests:
            cpu: "0.5"
        {{ end }}
        volumeMounts:
          - name: data
            mountPath: /joblogs
            subPath: joblogs
          - name: data
            mountPath: /wflowlogs
            subPath: wflowlogs
        env:
          - name: LOGSTASH_REDIS_HOST
            value: recast-backend-msg-queue.default.svc.cluster.local
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: control-center-data
