apiVersion: v1
kind: Secret
metadata:
  name: yadagewebuiauth
type: Opaque
data:
  oauth_secret: {{ .Values.yadage.oauth_secret | b64enc }}
  bearer_token: {{ .Values.yadage.bearer_token | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: yadage-ssl
type: Opaque
data:
  server.crt: |-
    {{ .Values.files.yadage_ssl_crt | b64enc }}
  server.key: |-
    {{ .Values.files.yadage_ssl_key | b64enc }}
