apiVersion: v1
kind: Secret
metadata:
  name: yadagewebuiauth
type: Opaque
data:
  bearer_token: {{ .Values.yadage.bearer_token | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: yadagewebui-oauth
type: Opaque
data:
  app_id: {{ .Values.OAuth.yadage_service.app_id | b64enc }}
  secret: {{ .Values.OAuth.yadage_service.secret | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: yadage-ssl
type: Opaque
data:
  server.crt: |-
    {{ .Values.files.yadage_ssl_crt | b64enc }}
  server.key: |-
    {{ .Values.files.yadage_ssl_key | b64enc }}
