apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: control-center
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: control-center
    spec:
      containers:
      - name: control-center
        image: recast/control-center:git-master
        imagePullPolicy: IfNotPresent
        command: ['recast-control-center','server','--config','/secrets/config/config.yaml']
        resources:
          requests:
            cpu: "0.5"
        ports:
          - containerPort: 8000
            name: "http"
            hostPort: 443
        volumeMounts:
          - name: ssl
            mountPath: /secrets/ssl
            readOnly: true
          - name: config
            mountPath: /secrets/config
            readOnly: true
          - name: backendconfig
            mountPath: /secrets/backend
            readOnly: true
          - name: cephfs
            mountPath: /recastresults
            subPath: recastresults
            readOnly: true
        env:
          - name: RECAST_BACKENDCONFIGFILE
            value: /secrets/backend/backendconfig.yml
          - name: RECAST_SSL_CERTFILE
            value: /secrets/ssl/server.crt
          - name: RECAST_SSL_KEYFILE
            value: /secrets/ssl/server.key
          - name: RECAST_APIURL
            value: https://frontend.default.svc.cluster.local:81/
          - name: RECAST_SSL_VERIFY
            value: 'false'
          - name: RECAST_BASEURL
            value: https://recast-control.cern.ch
          - name: RECAST_RESULT_BASE
            value: /recastresults
          - name: RECAST_BACKENDCONFIGURL
            value: https://raw.githubusercontent.com/recast-hep/recast-backend/master/recastbackend/resources/backendconfig.yml
          - name: RECAST_WORKFLOW_SERVER
            value: http://wflow-server.default.svc.cluster.local
          - name: RECAST_PROCDB_REDIS_HOST
            value: recast-backend-msg-queue.default.svc.cluster.local
          - name: RECAST_PROCDB_REDIS_PORT
            value: '6379'
          - name: RECAST_PROCDB_REDIS_DB
            value: '0'
      volumes:
      - name: ssl
        secret:
          secretName: control-center-ssl
      - name: config
        secret:
          secretName: control-center-config
      - name: backendconfig
        secret:
          secretName: control-center-backendconfig
      - name: cephfs
        persistentVolumeClaim:
          claimName: control-center-data
---
apiVersion: v1
kind: Service
metadata:
  name: control-center
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 32443
    name: http
    protocol: TCP
  selector:
    app: control-center
