apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: lukasheinrich/recast-frontend
        imagePullPolicy: IfNotPresent
        command: ['recast-frontend','server','--config','/secrets/config/config.yaml']
        ports:
          - containerPort: 5001
            name: http
            hostPort: 444
        volumeMounts:
          - name: ssl
            mountPath: /secrets/ssl
            readOnly: true
          - name: config
            mountPath: /secrets/config
            readOnly: true
        env:
          - name: RECAST_SSL_CERT
            value: /secrets/ssl/server.crt
          - name: RECAST_SSL_KEY
            value: /secrets/ssl/server.key
          - name: RECAST_ORCID_REDIRECT_URI
            value: https://recast-frontend-beta.cern.ch/login
      - name: postgres
        image: postgres:latest
        volumeMounts:
          - name: cephfs
            mountPath: /pgdata
            subPath: frontenddbdata
        env:
          - name: PGDATA
            value: /pgdata
        ports:
          - containerPort: 5432
            name: postgres
      - name: api
        image: lukasheinrich/recast-rest-server
        imagePullPolicy: IfNotPresent
        command: ['bash','-c','sleep 10 && recast-api server --config /secrets/config/config.yaml']
        env:
          - name: RECAST_SSL_CERT
            value: /secrets/ssl/server.crt
          - name: RECAST_SSL_KEY
            value: /secrets/ssl/server.key
        volumeMounts:
          - name: ssl
            mountPath: /secrets/ssl
            readOnly: true
          - name: config
            mountPath: /secrets/config
            readOnly: true
        ports:
          - containerPort: 5000
            name: rest
            hostPort: 445
      volumes:
      - name: ssl
        secret:
          secretName: frontend-ssl
      - name: config
        secret:
          secretName: frontend-config
      - name: cephfs
        persistentVolumeClaim:
          claimName: frontend-data
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5001
    nodePort: 30443
    name: webserver
    protocol: TCP
  - port: 81
    targetPort: 5000
    nodePort: 30444
    name: restapi
    protocol: TCP
  selector:
    app: frontend
