apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yadage-service-webui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: yadage-service-webui
    spec:
      containers:
      - name: yadage-service-webui
        image: yadage/yadage-service:alpha
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "0.5"
        ports:
          - containerPort: 5000
            name: "http"
            hostPort: 446
        volumeMounts:
          - name: cephfs
            mountPath: /recastresults
            subPath: recastresults
            readOnly: true
        env:
          - name: YADAGE_WORKFLOW_SERVER
            value: http://wflow-server.default.svc.cluster.local
          - name: YADAGE_SHIPTARGET_USER
            value: root
          - name: YADAGE_SHIPTARGET_HOST
            value: recast-backend-shiptarget.default.svc.cluster.local
          - name: YADAGE_SHIPTARGET_PORT
            value: '2022'
          - name: YADAGE_RESULTBASE
            value: /recastresults/yadagesvc
          - name: YADAGE_WORKFLOW_QUEUE
            value: recast_yadage_queue
      volumes:
      - name: cephfs
        persistentVolumeClaim:
          claimName: control-center-data
---
apiVersion: v1
kind: Service
metadata:
  name: yadage-service-webui
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32453
    targetPort: 5000
    name: http
    protocol: TCP
  selector:
    app: yadage-service-webui
