apiVersion: v1
kind: PersistentVolume
metadata:
  name: recast-cluster-pv-02
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - "ReadWriteMany"
  cephfs:
    monitors:
    - 128.142.36.227:6790
    - 128.142.39.77:6790
    - 128.142.39.144:6790
    path: /volumes/_nogroup/ba84a310-7ac9-467a-9c6f-bb0a54aceaed
    user: recast-cephfs-user
    secretRef:
      name: ceph-secret-recastauth
      readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: frontend-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
