version: '2'
services:
  plugin:
    image: lukasheinrich/recast-cap-demo
    command: bash -c 'cd /workdirsdata && celery worker -A recastbackend.fromenvapp:app -l debug -Q $$RECAST_QUEUE --concurrency 1'
    environment:
      - C_FORCE_ROOT=yes
      - RECAST_CELERY_REDIS_HOST=$HEADNODE
      - RECAST_CELERY_REDIS_PORT=6379
      - RECAST_CELERY_REDIS_DB=0
      - RECAST_QUEUE=recast_cap_queue
      - RECAST_SHIP_USER=root
      - RECAST_SHIP_HOST=$HEADNODE
      - RECAST_SHIP_PORT=22
      - RECAST_IN_DOCKER_WORKDIRS_VOL=$RECAST_IN_DOCKER_WORKDIRS_VOL
      - PACKTIVITY_WITHIN_DOCKER=true
      - RECAST_QUARANTINE_DIR=/quarantinedata
      - RECAST_YADAGEBACKEND=multiproc:4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.ssh:/root/.ssh
      - $RECAST_IN_DOCKER_WORKDIRS_VOL:/workdirsdata
      - $RECAST_IN_DOCKER_QUARANTINE_VOL:/quarantinedata
