apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 8
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: recast/cap-demo-worker
        imagePullPolicy: Always
        command:
        - sh
        - '-c'
        - >-
          cp ~/.ssh/rsa.key ~/.ssh/id_rsa &&
          chmod +x /secrets/auth/*.sh &&
          chmod 0400 /secrets/auth/privkey.pem &&
          cp -r /secrets/auth/* /sister_secrets &&
          chmod 0400 ~/.ssh/id_rsa &&
          ssh-keyscan -p 2022 -t rsa ${RECAST_SHIP_HOST} |sed "s|\(^.*.cluster.local\)|[\1]:2022|" > ~/.ssh/known_hosts &&
          celery worker -A recastcelery.fromenvapp:app -l debug -Q ${RECAST_QUEUE} --concurrency 2
        workingDir: /srv/workerdata
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: workerdata
            mountPath: /srv/workerdata
          - name: ssh
            mountPath: /root/.ssh
          - name: auth
            mountPath: /secrets/auth
          - name: sistersauth
            mountPath: /sister_secrets
        env:
          - name: RECAST_CELERY_REDIS_HOST
            value: control-center-internal.default.svc.cluster.local            
          - name: RECAST_CELERY_REDIS_PORT
            value: '6379'
          - name: RECAST_CELERY_REDIS_DB
            value: '0'
          - name: RECAST_QUEUE
            value: 'recast_cap_queue'
          - name: RECAST_SHIP_USER
            value: root
          - name: RECAST_SHIP_HOST
            value: control-center-internal.default.svc.cluster.local
          - name: RECAST_SHIP_PORT
            value: '2022'
          - name: RECAST_DOCKERHOST
            value: hello
          - name: RECAST_YADAGEBACKEND
            value: multiproc:4
          - name: C_FORCE_ROOT
            value: 'true'
          - name: RECAST_QUARANTINE_DIR
            value: /srv/workerdata/quarantine
          - name: PACKTIVITY_AUTH_LOCATION
            value: /srv/recast_auth
          - name: PACKTIVITY_CVMFS_SOURCE
            value: voldriver
          - name: PACKTIVITY_WITHIN_DOCKER
            value: 'true'
        resources:
          requests:
            cpu: "8"
      volumes:
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
      - name: workerdata
        hostPath:
          path: /srv/workerdata
      - name: sistersauth
        hostPath:
          path: /srv/recast_auth
      - name: ssh
        secret:
          secretName: control-center-ssh
      - name: auth
        secret:
          secretName: atlas-auth
      nodeSelector:
        workernode: 'true'
