apiVersion: v1
kind: PersistentVolume
metadata:
  name: recast-cluster-pv-01
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 0.1Gi
  hostPath:
    path: /Users/lukas/Code/recastdev/data/pv0001/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: control-center-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 0.1Gi
