apiVersion: v1
kind: PersistentVolume
metadata:
  name: recast-cluster-pv-02
spec:
  capacity:
    storage: 0.1Gi
  accessModes:
  - "ReadWriteMany"
  hostPath:
    path: /data/pv0002
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: frontend-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 0.1Gi
