apiVersion: v1
kind: PersistentVolume
metadata:
  name: recast-cluster-pv-03
spec:
  capacity:
    storage: 0.1Gi
  accessModes:
  - "ReadWriteMany"
  hostPath:
    path: /data/pv0003/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: worker-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 0.1Gi
