apiVersion: v1
kind: Service
metadata:
  name: control-center-internal
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  - port: 2022
    targetPort: 22
    name: ssh
  selector:
    app: control-center
