apiVersion: v1
kind: Service
metadata:
  name: control-center
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 32443
    name: http
    protocol: TCP
  selector:
    app: control-center
