apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
  - port: 80 
    targetPort: 5001
    nodePort: 30443
    name: webserver
    protocol: TCP
  - port: 81
    targetPort: 5000
    nodePort: 30443
    name: restapi
    protocol: TCP
  selector:
    app: frontend
