{{ if eq .Values.Storage.Type "cephfs"}}
apiVersion: v1
data:
  key: {{ .Values.Storage.CephFS.AuthKey | b64enc}}
kind: Secret
metadata:
  name: ceph-secret
  labels:
    component: infra
type: Opaque
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: recast-cluster-pv-01
  labels:
    component: infra
spec:
  capacity:
    storage: {{ .Values.Storage.CCSize }}
  accessModes:
  - "ReadWriteMany"
  cephfs:
    monitors:
    {{- range .Values.Storage.CephFS.Monitors }}
    - {{ . | quote }}
    {{- end }}
    user: {{ .Values.Storage.CephFS.User }}
    secretRef:
      name: ceph-secret
    path: {{ .Values.Storage.CephFS.Path }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: recast-cluster-pv-02
  labels:
    component: infra
spec:
  capacity:
    storage: {{ .Values.Storage.WorkerSize }}
  accessModes:
  - "ReadWriteMany"
  cephfs:
    monitors:
    {{- range .Values.Storage.CephFS.Monitors }}
    - {{ . | quote }}
    {{- end }}
    user: {{ .Values.Storage.CephFS.User }}
    secretRef:
      name: ceph-secret
    path: {{ .Values.Storage.CephFS.Path }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: recast-cluster-pv-03
  labels:
    component: infra
spec:
  capacity:
    storage: {{ .Values.Storage.FrontendSize }}
  accessModes:
  - "ReadWriteMany"
  cephfs:
    monitors:
    {{- range .Values.Storage.CephFS.Monitors }}
    - {{ . | quote }}
    {{- end }}
    user: {{ .Values.Storage.CephFS.User }}
    secretRef:
      name: ceph-secret
    path: {{ .Values.Storage.CephFS.Path }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: recast-cluster-pv-04
  labels:
    component: infra
spec:
  capacity:
    storage: {{ .Values.Storage.InfraSize }}
  accessModes:
  - "ReadWriteMany"
  cephfs:
    monitors:
    {{- range .Values.Storage.CephFS.Monitors }}
    - {{ . | quote }}
    {{- end }}
    user: {{ .Values.Storage.CephFS.User }}
    secretRef:
      name: ceph-secret
    path: {{ .Values.Storage.CephFS.Path }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: recast-cluster-pv-05
  labels:
    component: infra
spec:
  capacity:
    storage: {{ .Values.Storage.WorkflowSvcSize }}
  accessModes:
  - "ReadWriteMany"
  cephfs:
    monitors:
    {{- range .Values.Storage.CephFS.Monitors }}
    - {{ . | quote }}
    {{- end }}
    user: {{ .Values.Storage.CephFS.User }}
    secretRef:
      name: ceph-secret
    path: {{ .Values.Storage.CephFS.Path }}
{{ end }}
